-- ============================================================
-- Seed: 75 FyQ Topics (35 Física + 40 Química)
-- ============================================================

insert into public.topics (code, title, subject, description, order_index) values

-- FÍSICA (35 topics)
('FIS-01', 'Magnitudes físicas y vectores',              'fisica', 'Sistema Internacional, análisis dimensional, operaciones vectoriales', 1),
('FIS-02', 'Cinemática: MRU y MRUA',                    'fisica', 'Movimiento rectilíneo uniforme y uniformemente acelerado', 2),
('FIS-03', 'Cinemática: movimiento curvilíneo',          'fisica', 'Tiro parabólico, movimiento circular', 3),
('FIS-04', 'Dinámica: Leyes de Newton',                  'fisica', 'Principios de la dinámica, fuerzas y aceleración', 4),
('FIS-05', 'Rozamiento y planos inclinados',             'fisica', 'Fuerzas de rozamiento estático y cinético', 5),
('FIS-06', 'Trabajo y potencia',                        'fisica', 'Trabajo de una fuerza, potencia, rendimiento', 6),
('FIS-07', 'Energía mecánica y conservación',           'fisica', 'Energía cinética, potencial y principio de conservación', 7),
('FIS-08', 'Momento lineal e impulso',                  'fisica', 'Cantidad de movimiento, impulso, choque elástico e inelástico', 8),
('FIS-09', 'Gravitación universal',                     'fisica', 'Ley de gravitación, campos gravitatorios, satélites', 9),
('FIS-10', 'Movimiento armónico simple (MAS)',           'fisica', 'Péndulo simple, sistema masa-muelle', 10),
('FIS-11', 'Ondas mecánicas',                           'fisica', 'Propiedades de las ondas, ecuación de onda', 11),
('FIS-12', 'Sonido y acústica',                         'fisica', 'Intensidad sonora, efecto Doppler, resonancia', 12),
('FIS-13', 'Temperatura y calor',                       'fisica', 'Escalas termométricas, dilatación, calor específico', 13),
('FIS-14', 'Primer principio de la termodinámica',       'fisica', 'Energía interna, trabajo termodinámico, ciclos', 14),
('FIS-15', 'Segundo principio de la termodinámica',      'fisica', 'Entropía, máquinas térmicas, ciclo de Carnot', 15),
('FIS-16', 'Estática de fluidos',                       'fisica', 'Presión, principio de Arquímedes, principio de Pascal', 16),
('FIS-17', 'Dinámica de fluidos',                       'fisica', 'Ecuación de continuidad, Bernoulli', 17),
('FIS-18', 'Óptica geométrica',                         'fisica', 'Reflexión, refracción, lentes y espejos', 18),
('FIS-19', 'Óptica ondulatoria',                        'fisica', 'Interferencia, difracción, polarización', 19),
('FIS-20', 'Campo eléctrico',                           'fisica', 'Ley de Coulomb, campo eléctrico, líneas de campo', 20),
('FIS-21', 'Potencial eléctrico y energía',             'fisica', 'Potencial, diferencia de potencial, trabajo eléctrico', 21),
('FIS-22', 'Condensadores',                             'fisica', 'Capacidad, energía almacenada, dieléctricos', 22),
('FIS-23', 'Corriente eléctrica y circuitos DC',        'fisica', 'Ley de Ohm, resistencias, circuitos mixtos, leyes de Kirchhoff', 23),
('FIS-24', 'Campo magnético',                           'fisica', 'Fuentes del campo, ley de Biot-Savart, ley de Ampère', 24),
('FIS-25', 'Fuerzas magnéticas',                        'fisica', 'Fuerza sobre cargas y conductores, aplicaciones', 25),
('FIS-26', 'Inducción electromagnética',                'fisica', 'Ley de Faraday-Lenz, autoinducción, transformadores', 26),
('FIS-27', 'Corriente alterna',                         'fisica', 'Circuitos RC, RL y RLC, potencia en CA, resonancia', 27),
('FIS-28', 'Ondas electromagnéticas y espectro',        'fisica', 'Ecuaciones de Maxwell, espectro EM, polarización', 28),
('FIS-29', 'Relatividad especial',                      'fisica', 'Postulados, dilatación temporal, contracción espacial, E=mc²', 29),
('FIS-30', 'Física cuántica: dualidad onda-corpúsculo', 'fisica', 'Efecto fotoeléctrico, hipótesis de Broglie, principio de incertidumbre', 30),
('FIS-31', 'Modelo atómico de Bohr y espectros',        'fisica', 'Niveles de energía, series espectrales', 31),
('FIS-32', 'Física nuclear: estructura y estabilidad',  'fisica', 'Núcleo atómico, energía de enlace, defecto de masa', 32),
('FIS-33', 'Radiactividad y desintegración nuclear',    'fisica', 'Tipos de radiación, ley de desintegración, vida media', 33),
('FIS-34', 'Fisión, fusión y aplicaciones nucleares',   'fisica', 'Reacciones nucleares, reactores, usos médicos e industriales', 34),
('FIS-35', 'Partículas elementales',                    'fisica', 'Modelo estándar, quarks, leptones, bosones', 35),

-- QUÍMICA (40 topics)
('QUI-01', 'Estructura atómica',                        'quimica', 'Modelos atómicos, número atómico y másico, isótopos', 36),
('QUI-02', 'Configuración electrónica',                 'quimica', 'Números cuánticos, orbitales, principio de Aufbau, Hund', 37),
('QUI-03', 'Tabla periódica: propiedades periódicas',   'quimica', 'Radio atómico, energía de ionización, afinidad electrónica', 38),
('QUI-04', 'Enlace iónico',                             'quimica', 'Formación, energía reticular, ciclo de Born-Haber', 39),
('QUI-05', 'Enlace covalente',                          'quimica', 'Teoría del enlace de valencia, hibridación, polaridad', 40),
('QUI-06', 'Geometría molecular (VSEPR)',                'quimica', 'Pares de electrones enlazantes y no enlazantes, geometrías', 41),
('QUI-07', 'Fuerzas intermoleculares',                  'quimica', 'Van der Waals, puentes de hidrógeno, enlace metálico', 42),
('QUI-08', 'Estequiometría: mol y masa molar',          'quimica', 'Concepto de mol, número de Avogadro, pureza y rendimiento', 43),
('QUI-09', 'Estequiometría: reacciones químicas',       'quimica', 'Ajuste, reactivo limitante, cálculos estequiométricos', 44),
('QUI-10', 'Gases: leyes y gas ideal',                  'quimica', 'Leyes de Boyle, Charles, Gay-Lussac, ecuación de gas ideal', 45),
('QUI-11', 'Disoluciones: concentración',               'quimica', 'Molaridad, molalidad, fracción molar, diluciones', 46),
('QUI-12', 'Propiedades coligativas',                   'quimica', 'Descenso crioscópico, elevación ebullioscópica, presión osmótica', 47),
('QUI-13', 'Termoquímica: entalpía',                    'quimica', 'Ley de Hess, entalpía de formación, de combustión', 48),
('QUI-14', 'Termodinámica química: entropía y ΔG',      'quimica', 'Entropía, energía de Gibbs, espontaneidad', 49),
('QUI-15', 'Cinética química: velocidad de reacción',   'quimica', 'Ley de velocidad, orden de reacción, factores que afectan', 50),
('QUI-16', 'Cinética química: mecanismos y catálisis',  'quimica', 'Etapa determinante, energía de activación, catalizadores', 51),
('QUI-17', 'Equilibrio químico: Kc y Kp',               'quimica', 'Constante de equilibrio, relación Kc-Kp, cociente de reacción', 52),
('QUI-18', 'Principio de Le Chatelier',                 'quimica', 'Perturbaciones del equilibrio: T, P, concentración', 53),
('QUI-19', 'Equilibrio ácido-base: teorías',            'quimica', 'Arrhenius, Brønsted-Lowry, Lewis, pares conjugados', 54),
('QUI-20', 'pH y cálculos ácido-base',                  'quimica', 'pH, pOH, ácidos fuertes y débiles, Ka y Kb', 55),
('QUI-21', 'Hidrólisis y soluciones tampón',            'quimica', 'Hidrólisis de sales, efecto tampón, ecuación de Henderson-Hasselbalch', 56),
('QUI-22', 'Equilibrio de precipitación (Kps)',         'quimica', 'Producto de solubilidad, precipitación selectiva', 57),
('QUI-23', 'Electroquímica: pilas y potencial',         'quimica', 'Pilas galvánicas, potencial estándar, ecuación de Nernst', 58),
('QUI-24', 'Electroquímica: electrólisis',              'quimica', 'Leyes de Faraday, cálculos electrolíticos', 59),
('QUI-25', 'Nomenclatura inorgánica',                   'quimica', 'Óxidos, hidróxidos, ácidos, sales: nomenclatura IUPAC', 60),
('QUI-26', 'Reacciones redox: ajuste y cálculo',        'quimica', 'Número de oxidación, semirreacciones, método ion-electrón', 61),
('QUI-27', 'Química orgánica: nomenclatura y grupos',   'quimica', 'Cadenas carbonadas, isomería, grupos funcionales', 62),
('QUI-28', 'Alcanos y cicloalcanos',                    'quimica', 'Propiedades, conformaciones, reacciones de sustitución radical', 63),
('QUI-29', 'Alquenos y alquinos',                       'quimica', 'Insaturaciones, adición electrófila, regla de Markovnikov', 64),
('QUI-30', 'Compuestos aromáticos',                     'quimica', 'Benceno, aromaticidad, sustitución electrófila aromática', 65),
('QUI-31', 'Alcoholes, fenoles y éteres',               'quimica', 'Propiedades, oxidación de alcoholes, enlaces de hidrógeno', 66),
('QUI-32', 'Aldehídos y cetonas',                       'quimica', 'Reacciones de adición nucleófila, prueba de Tollens', 67),
('QUI-33', 'Ácidos carboxílicos y derivados',           'quimica', 'Reacciones de esterificación, amidas, anhídridos', 68),
('QUI-34', 'Aminas y amidas',                           'quimica', 'Propiedades básicas, síntesis de proteínas', 69),
('QUI-35', 'Polímeros y macromoléculas',                'quimica', 'Adición, condensación, plásticos, elastómeros, fibras', 70),
('QUI-36', 'Reacciones orgánicas: sustitución',         'quimica', 'SN1, SN2, eliminación E1/E2, factores determinantes', 71),
('QUI-37', 'Biomoléculas: glúcidos y lípidos',          'quimica', 'Monosacáridos, disacáridos, ácidos grasos, triglicéridos', 72),
('QUI-38', 'Biomoléculas: proteínas y ácidos nucleicos', 'quimica', 'Aminoácidos, estructura proteica, ADN, ARN', 73),
('QUI-39', 'Química verde y sostenibilidad',            'quimica', '12 principios, economía atómica, disolventes verdes', 74),
('QUI-40', 'Técnicas de laboratorio y análisis',        'quimica', 'Seguridad, valoraciones, cromatografía, espectroscopía básica', 75);
